package web.test.pojo;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.t_id
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.t_name
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.t_model_number
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    private String modelNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.t_version
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.t_group
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    private String group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.t_desc
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_product.t_json
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    private String json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.t_id
     *
     * @return the value of test_product.t_id
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.t_id
     *
     * @param id the value for test_product.t_id
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.t_name
     *
     * @return the value of test_product.t_name
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.t_name
     *
     * @param name the value for test_product.t_name
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.t_model_number
     *
     * @return the value of test_product.t_model_number
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.t_model_number
     *
     * @param modelNumber the value for test_product.t_model_number
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public void setModelNumber(String modelNumber) {
        this.modelNumber = modelNumber == null ? null : modelNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.t_version
     *
     * @return the value of test_product.t_version
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.t_version
     *
     * @param version the value for test_product.t_version
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.t_group
     *
     * @return the value of test_product.t_group
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.t_group
     *
     * @param group the value for test_product.t_group
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public void setGroup(String group) {
        this.group = group == null ? null : group.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.t_desc
     *
     * @return the value of test_product.t_desc
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.t_desc
     *
     * @param desc the value for test_product.t_desc
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_product.t_json
     *
     * @return the value of test_product.t_json
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_product.t_json
     *
     * @param json the value for test_product.t_json
     *
     * @mbggenerated Tue Aug 11 20:48:07 CST 2015
     */
    public void setJson(String json) {
        this.json = json == null ? null : json.trim();
    }
}