package web.test.pojo;

public class UserProductRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user_product_rel.t_user_id
     *
     * @mbggenerated Sun Aug 16 09:40:30 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user_product_rel.t_product_id
     *
     * @mbggenerated Sun Aug 16 09:40:30 CST 2015
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user_product_rel.t_user_id
     *
     * @return the value of test_user_product_rel.t_user_id
     *
     * @mbggenerated Sun Aug 16 09:40:30 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user_product_rel.t_user_id
     *
     * @param userId the value for test_user_product_rel.t_user_id
     *
     * @mbggenerated Sun Aug 16 09:40:30 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user_product_rel.t_product_id
     *
     * @return the value of test_user_product_rel.t_product_id
     *
     * @mbggenerated Sun Aug 16 09:40:30 CST 2015
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user_product_rel.t_product_id
     *
     * @param productId the value for test_user_product_rel.t_product_id
     *
     * @mbggenerated Sun Aug 16 09:40:30 CST 2015
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }
}