package web.test.mapper;

import web.test.pojo.UserProductRel;

public interface UserProductRelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user_product_rel
     *
     * @mbggenerated Sun Aug 16 09:40:30 CST 2015
     */
    int deleteByPrimaryKey(UserProductRel key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user_product_rel
     *
     * @mbggenerated Sun Aug 16 09:40:30 CST 2015
     */
    int insert(UserProductRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user_product_rel
     *
     * @mbggenerated Sun Aug 16 09:40:30 CST 2015
     */
    int insertSelective(UserProductRel record);
}